brand:
  sample:
    name: sample
    # Config UserData ユーザーデータ設定
    user:
      db: td_audience_studio
      tbl: customers
      user_id: user_id
      # If you don't have colmuns 'na'  カラムを持っていない場合 na を入力
      email: 
        row: na
        hash: mail_hash
      phone: 
        # EX)Phone Number 080-2222-3333
        # META - '818022223333' (記号、文字、すべての先行ゼロを削除,国番号)
        # GOOGLE/LINE/YAHOO - '+818022223333' (E.164:先行ゼロ/ハイフンを削除,+国番号)
        row: na
        hash_meta: na
        hash_e164: na
      gender: gender_name
      male: 男性
      female: 女性
      birth_date: na
      first_name: na
      last_name: na
      prefecture: prefectures
      city: na
      zip_code: na
      country: JP
      currency: JPY
      ifa: na
      line_uid: na
    # Offline Purchase Data オフライン購買データ設定
    offline:
      check: true
      db: td_audience_studio #set web_log database
      tbl: purchase_offline #set web_log table
      user_id: user_id #
      amount: amount
      order_time_unix: prder_date
      product: product
      order_id: order_id
      time_filter: TD_TIME_PARSE(prder_date,'JST')
      cnv_config:
    # Online Purchase Data オンライン購買データ設定
    online:
      check: true
      db: td_audience_studio #set web_log database
      tbl: agg_weblog #set web_log table
      user_id: user_id_comp #UserID
      order_id: url_extract_parameter(td_url, 'orderID')
      url: td_url
      title: td_title
      referrer: td_referrer
      user_agent: td_user_agent
      ip: td_ip
      fbp: na
      fbc: na
      yclid: na
      yjr_yjad: na
      lt_cid: na
      amount: 1000
      cnv_url:
        - thanks
    meta:
      offline: false 
      online: false
      connector: CONNECTOR_NAME
      custom_data: json_format(CAST(MAP(ARRAY['currency', 'value'], ARRAY[currency, cast(amount as VARCHAR)]) as JSON))
    google_upload_enhanced_for_web:
      check: false
      type: upload_enhanced_for_web 
      connector: CONNECTOR_NAME
      customer_id: 111111
      conversion_action_id: 111111
    google_upload_enhanced_for_lead:
      check: false
      type: upload_enhanced_for_lead 
      connector: CONNECTOR_NAME
      customer_id: 111111
      conversion_action_id: 111111
    google_upload_offline_click_conversion:
      check: false
      type: upload_offline_click_conversion 
      connector: CONNECTOR_NAME
      customer_id: 111111
      conversion_action_id: 111111
    google_upload_call_conversion:
      check: false
      type: upload_call_conversion 
      connector: CONNECTOR_NAME
      customer_id: 111111
      conversion_action_id: 111111
    yahoo:
      check: true
      connector: CONNECTOR_NAME
      yahoo_app_id: 111111
      yahoo_ydn_conv_io: 1EALEzSJBNabcdEFGBE1
      yahoo_ydn_conv_label: AB0ABCDEFGHIJKLMNOP123456
    line:
      check: true
      connector: CONNECTOR_NAME
      line_tag_id: tag_id_1234
      access_token: abc1234

